[package]
name = "ammonia"
version = "3.1.4"
authors = ["Michael Howell <michael@notriddle.com>"]
description = "HTML Sanitization"
keywords = [ "sanitization", "html", "security", "xss" ]
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ammonia/"
repository = "https://github.com/rust-ammonia/ammonia"
categories = [ "web-programming", "text-processing" ]
edition = "2018"

[dependencies]
html5ever = "0.26"
markup5ever_rcdom = "0.2"
maplit = "1.0"
tendril = "0.4"
url = "2"
lazy_static = "1.3"

[dev-dependencies]
version-sync = "0.9"
env_logger = "0.9"
